### ISSUE TITLE
Broken links (going to github)

### ISSUE THREAD

**Issue by n8henrie** [quicksilver/Documentation#1]
Currently:

https://docs.qsapp.com/documentation/applescripts#three-pane-applescripts

First link for `Run command in shell with arguments` is a 404: <https://github.com/quicksilver/Documentation/blob/main/Run_command_in_shell_with_arguments/README.md>

Should link to <https://docs.qsapp.com/documentation/run_command_in_shell_with_arguments> (or less likely to <https://github.com/quicksilver/Documentation/blob/main/Run_command_in_shell_with_arguments.md>).

Source: https://github.com/quicksilver/Documentation/blob/7fd9570c19e9dc6a3527101d3866fd48b53cb73e/AppleScripts.md?plain=1#L103

At first I thought just needed to fix the relative URL, but looks like it's being reconstructed into an absolute URL at build time (and therefore linking to github instead of docs.qsapp.com).

Looks like same issue for `Convert Units To`

I'll have to read about gitbooks.

**Comment by pjrobertson** [comment]
Fixed by latest commits. Had to convert all URLs to absolute URLs. Not ideal but it'll do for now
